import type { Metadata } from 'next'

import './globals.css'

import { clientEnvironment } from 'src/environments/client'
import { ReactQueryProvider } from 'src/providers/ReactQueryProvider'
import { Inter } from 'next/font/google'
import './globals.css'
import { ChildrenProps } from 'src/types/common'
import { NextAuthProvider } from 'src/providers/NextAuthProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  description: 'Generated by create next app',
  title: 'Create Next App',
}

export default async function RootLayout({ children }: ChildrenProps) {
  return (
    <html>
      <body
        className={inter.className}
        suppressHydrationWarning={clientEnvironment.suppressHydrationWarning}
      >
        <NextAuthProvider>
          <ReactQueryProvider>{children}</ReactQueryProvider>
        </NextAuthProvider>
      </body>
    </html>
  )
}
